export const GET_USER_LIST: string = 'GET_USER_LIST';
export const GET_USER_LIST_SUCCES: string = 'GET_USER_LIST_SUCCESS';
export const UPDATE_USER_LIST_ON_SELECT: string = 'UPDATE_USER_LIST_ON_SELECT';

export const GET_USER_DETAILS: string = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS: string = 'GET_USER_DETAILS_SUCCESS';